#!/bin/bash

nmappers=2
nreducers=2

pids=""

# ghc --make KMeans || exit 1

for i in $( seq 1 ${nmappers} )
do
  ./KMeans -cfgRole=MAPPER  +RTS -K20000000&
  pid=$!
  pids="$pids $pid"
done

for i in $( seq 1 ${nreducers} )
do
  ./KMeans -cfgRole=REDUCER  +RTS -K20000000&
  pid=$!
  pids="$pids $pid"
done

./KMeans -cfgRole=MASTER  +RTS -K20000000

kill $pids
